# 動態網頁爬蟲 - API Request

* 了解 API Request 用於動態網頁爬蟲的原理
* 能夠使用 API Request 撰寫動態網頁爬蟲

## 作業目標


* 根據範例使用 API 取出 高雄市小港區 2019 年 空氣品質 資料，並用一個適合的資料結構儲存
* Hint: 將所有資料存在一個變數當中

In [1]:
import requests
url = 'https://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx'
payload = {
    'ScriptManager1': 'ctl05$UpdatePanel1|ctl05$btnQuery',
    '__VIEWSTATE': '3ACAZhYMYiMAXbQbwzX2zICCMDGTLpdl+2S3o74IyI8nqHWvTjza2NLdoMxYyvgNatJ7XUxQvvVRD8H0ZTyf93MTOlZkqGMifI3lrwdmGlLw4qFQetgClw7drd6LqTnOkOzQNxhOB3rxC/65tPlDIKu67fcXyw1gdwY+YYkZkLUZZ97015hsIknGucFKwIhznlsbxiWZ9ABrE0mUta8lqjuIWjeLr6vvZx90ZidjQAViBCWb7FkR63Wqn2WpbuA3hw8Hds+aOrykf2I2TQs3jXQKeS0XJ/w50zSyoTz6h0Lr9I24z/BdRmrpKmQsg+rEX79B7FyY8G+Zq4Mq+yfmA+1KSfFe+MJw1E9pZqMnOivGw+U5JmCU1+wSsllQct/9m+K0HnnoEyCgeQDyfyFMTxF2UU1BYOLOqizcrFtqDRIrTOkdmSx1V+XklUhEcU16MWpczMMk51o6tVb2Sc++vgNyhv/+ituuY2estFL61fwlRG0pXFj88uDVRXjHCU/IOILeRS7GyYejDQspNE9JrLRJa4uv9+/Rk3LMsERvhHq6j6DJMpUKE1zGfKeiDtktfWBA6IbZekaToRkMtUKWyXOcMwpHD250BqNpXyeMPAooMcShaqRLReDZugq4fp4ntHIvokXjqZhwlviKD4m63+IkfStrSeWujpSuqePoCIdWcNIUAssHBnuqnqnwU2Ua5AkF8jIL59xqX/eNPuOH0K8DVeDG6fRiFH+gSLF1736tJ8mjfE7zayZA40vqrZfnQHBYpPjUm5YF9Qu6BZZ5jw7Ioav0eRwdl4SPsu0Woz1HLgP5o2SOzY5jsgL3nun1fkeedxJtQLEK0HoI+V3vsbBTHbBvwd8XRi7r+ysE5Sj6WaC3/W+k22JdHmxBCkQLfnWZDQvayabwKtFprWE0jmWZl4564xJMuKW0Mggzp5GmKOeCVQ3bUapqCN+iEO/X4vZewAhdQGunHUPU8Fu3cM2XEsDTM1PM5opeQD3mcNedyeJ8EoOKBPJ8uUtc2B/JrBesrhm88YhXnLP9ZZJZjD3iKS7fOdkKhUwHoY3WM28H5vYmYLLZksXWAQeY7pckk5xlINMjafrI7EsOaLDNXNZLaD5sztOcx7mSetuChEM0vbc+iKDuSKEaumU/sP38EXfr7qxnTLl5vK+QQzWJZLonxubIv1xiVduG1rc2swUHvLYtsSISdNiEXEN9OKBXvtAN47Xz89bKGXfchKsouQokX1w3e1xTnKU4foN0Nv2g7AOs9NAQO+ntd+fIBXDftnH4outeOTgluLPqH1rbSKCf86YbDvjHkebUqRKdjYxk+heDUyVgVd4v9I+9k2kSAhdY36d7fZNYpGciWcpkeMoELIghxdjcHQrk6AKheQ9PdSRpZBh/IG91B09NFQmn8crtZPoKfSpM4Z3gpHrLH6gFC9KK6fiNYopTjhFXdtavgCfEcfSa5LuWKtBaUzKgN6sMu32+v6QbgaI/bq3MluNOLVR8CUbfc3naKAq+NQEw1QLO7wRHGuHH8VcyaG0lJ+yTW4P840hZPPCxtIO5DAtdvO/lwQ0YaOpHE5ijQNlJSEGAwGwbTfbW9SE/48HvMDrPtB8lB3VLsk+4E6x2PYN9n2v2RRFvuULNMVcODXSWSjSV6tC70X65qYrEpcb9mLc32Ly6MMXjp3yDxUz2o+Y4Mk6LUolyA4Ayzq751FSjIzJXz7RicD3q71QwTsSXHalWuDBEkGk8K+GNXuMNBtoSA942X/N2PVWYjTRx+7cQ4vFcpbsW7CFa8KpMZ6R74bVMG3bXIQGuM6740tLtrW6luzgivMVTcVQHlfRtfq0hy2b0KqFNzMhtCw3ZKpYwl9rAgNumViTSoTSGwnY9j0M7E6QzB1gVclVlVY/0hZD3IHJ2on8ic8iHhQ1ShZqeADccy4tKI9YrdZuWfu1/VwFHiuuipu5M/OS023q3RzScISoGpPQo/2FCNn0BAmAkf9AP5aW9AmNvo57vXm3PLjLmgkfJMUfnNY4dDX5UhyKJ2HL7OrEXGNsTXTqAXMRJqjHs3w0KZQxGDji1krT1Tn6sFaaVsJkcq3Py92rUuhUjSIbn/mUS26765VFrgIBedAb4bsPANxX5PcTzTv34J/ZrfRP/H2/bspG6kKwLrw6MDTVQyL72JZPghYXaYRVgCnHR3RNA5nlbZRDi+7vhugROwHG795+jxkPCmlxZPIYxttwsvmhia6lZ8Yz+9Jp7TMni/CZr+TTfxNV71FlfuTzRlRhO9F6hthRz11bTm+5sdPSLrjzXHQ+vlqa0/n6KIEHRY1xr0XFYfeIFuzVXjW2PDsG25pT+msqxfIWNACtiD8N4M1qoFhmBx5AMBsFXALlg7OxRwcW9Cks3o/R8wK8XVhweUbxFFcESCJpDaBQH4MuobaElcBalrh4ZdPiM6jhJ/r3l4VxfIU5JGi1u7kpcXt4SAtXdo0gRMslFHH9dgWPneLJXiDzemO/gb//Y21dchGrt+ll7vyAamqDVJSAIEbjj39tLiUtsI1S0KAFxjJA741uFaf3iVpPN5CUvq8PnSJ6aM3tzQ98TeyMb1GlgMgeYoJJGjzqPDw2GcKUYP+pJHJu9TR/axe2ThKUEa9ABpVFxV4qaO8EYcUvGqkQBmWv1Q2MmVy1omTSLxNm+r34BTqBilClydHYU31jiI9myPZlUpSeYeY8DGeZzqoai40KLQRd+CtxJvt3VakGRSRkyGmF6YKuY0dQTv1HOZpQCB6YnmU9XHptv5GZYmC+AAUgmKyL53hJNvoS29viBQEVBYObpxq1zv1Na1aDARgl1t7/XQeePYehC74S09Ftdt40LlzBX3KZaxrF96xo0f8/PJtmPLYK9YmLjvn3wnGPGC24tB4Rs83cCuV/sIA9ZSJDr0thBgyDfQwjOtJzOxYp/QcukduS8JRYGU/3wuMxmOH9Yt4b/nIgfMcbIFamH5t5dBgMqndV5HnA+FeYS/S+x1rjbkE5xoUv8zFCWvDSZYk+sVZo/GR1ygBBWQ69w705NwOOEnwsBmC9ryEVzSxIIofTORxZmg8Wr0MHzZ8qoGJPiop4T7IToEV48rFaN/Anhx/8cnm8iqY8T5YPnXkUE',
    '__VIEWSTATEGENERATOR': '0C858E1A',
    '__EVENTVALIDATION': 'Y2WEeaOOuJSLmAGwmYzzJ0qZqV10GNT/zati/8Spmy5fEfk1/3fQ2McYnKXmduDS7MFU0ICsxUJwOmlY+iCR9aFNeeqHpKnHW4uxNbHOg5kRU92dqyCpMS10C2Fj3wvlB06q+TWrGkw5DmQl9o4EZwmjzS2p+oS3mHlKXJYbFGSi7MepkrPnygYz7AxzmFbJHHTiwvrYjQZEN6zg0zsMW8a8nX9zzZWNq+T1BynzqehpmLZFOIYrvu9wATjYjhsCw8RrW2r6aNdiLO0TxGnOPpE3IRjcw8nJ7TDHPvryXMS2hDJliEUilxVKzkvoLHNVyRhj/dhC7T+yRnj94xj6hX0X/TJ/CD6rVB3n3GAex4hMQ20DgLA2gjKQW+hkT1LVswNEGDpF3m0qAUCv5j8JEqTMb+BPejkuezdKD5hPam7mmWduCQPmQUu3fIxHKEdjdoUaNnlKHYL/gCja/vWXwYXcCGyOFJdqiLCePYtFnwWH4GXrx7ImuuOM4eVlnwQdEk2RcTVyQAtVSyZ7Tnho2ryZ7u7BV3DG/i7eCQUpTn4b5PJWd60iiINw+hQahImJPPoFhLFfXlXb7sjg+58QyphvqZP2bIzcDBtZUDgR2pb/vpFiaI70tyd+p9XyKCDbQqMNxTW4QMpfhERXSUy7jzaL1Kpccw+m8iN/AFmH7uUug3HlgWc8vQz4EQHsekl/j9J6d48GfbTZ1MNWPLmX0+al8k1+6JPPkQK3Ei/42mf7tcZdwYFibBpY5hDiOIL2QHa8Piu4L8Y8cwsUz6iz5w5SNv63WFCkU8DAQ6BNem+2jgvmVVk8TPMnukyX66fDljW7Sag8IeKc+xq7uY5gigSYsLxQsugv0eWDBSdNKKrg2PeNZcUxW6nmwGGX56enifmuQBbGsxhVvy3DAsrc7fqqmWD/5M+XiYdSuYYUQ/Psi5Mt55zDTp38KXiSzE//cb4o2w==',
    'ctl05$ddlSite': '58',
    'ctl05$ddlYear': '2019',
    'ctl05$btnQuery': '查詢'
}
r = requests.post(url, data=payload)
r.status_code

200

![](https://imgur.com/obLkbFe.jpg)

In [3]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, 'html.parser')
table = soup.find('table', class_='TABLE_G')
items = table.find_all('tr')[1:]

In [4]:
d = {}
for i in items:
    if(len(i.find_all('td'))) == 5:
        param = i.find_all('td')[0].get_text()
        d[param] = {}
        month = i.find_all('td')[2].get_text()
        d[param][month] = i.find_all('td')[3].get_text()
    else:
        date = i.find_all('td')[0].get_text()
        d[param][date] = i.find_all('td')[1].get_text()
d

{'SO2': {'2019/01': '4.10',
  '2019/02': '3.30',
  '2019/03': '3.90',
  '2019/04': '3.40',
  '2019/05': '3.30',
  '2019/06': '4.10',
  '2019/07': '4',
  '2019/08': '4.60',
  '2019/09': '3.50',
  '2019/10': '3.20',
  '2019/11': '3.60'},
 'CO': {'2019/01': '0.67',
  '2019/02': '0.48',
  '2019/03': '0.50',
  '2019/04': '0.39',
  '2019/05': '0.38',
  '2019/06': '0.24',
  '2019/07': '0.28',
  '2019/08': '0.33',
  '2019/09': '0.32',
  '2019/10': '0.36',
  '2019/11': '0.46'},
 'O3': {'2019/01': '24.70',
  '2019/02': '29.40',
  '2019/03': '29.20',
  '2019/04': '30.40',
  '2019/05': '28.60',
  '2019/06': '16.30',
  '2019/07': '15.50',
  '2019/08': '19.70',
  '2019/09': '35.70',
  '2019/10': '44',
  '2019/11': '34.80'},
 'PM10': {'2019/01': '78',
  '2019/02': '57',
  '2019/03': '52',
  '2019/04': '42',
  '2019/05': '35',
  '2019/06': '20',
  '2019/07': '24',
  '2019/08': '27',
  '2019/09': '35',
  '2019/10': '50',
  '2019/11': '63'},
 'NOx': {'2019/01': '38.01',
  '2019/02': '25.62',
  '2019/03': '27.84',
  '2019/04': '21.83',
  '2019/05': '22.55',
  '2019/06': '17.15',
  '2019/07': '17.71',
  '2019/08': '19.66',
  '2019/09': '18.66',
  '2019/10': '19.50',
  '2019/11': '28.99'},
 'NO': {'2019/01': '7.95',
  '2019/02': '4.76',
  '2019/03': '5.41',
  '2019/04': '4.16',
  '2019/05': '4.58',
  '2019/06': '5.08',
  '2019/07': '5.16',
  '2019/08': '5.17',
  '2019/09': '3.63',
  '2019/10': '3.50',
  '2019/11': '5.21'},
 'NO2': {'2019/01': '30.06',
  '2019/02': '20.86',
  '2019/03': '22.43',
  '2019/04': '17.68',
  '2019/05': '17.98',
  '2019/06': '12.08',
  '2019/07': '12.54',
  '2019/08': '14.49',
  '2019/09': '15.03',
  '2019/10': '15.99',
  '2019/11': '23.78'},
 'THC': {'2019/01': '2.27',
  '2019/02': '2.11',
  '2019/03': '2.12',
  '2019/04': '2.02',
  '2019/05': '2.02',
  '2019/06': '1.92',
  '2019/07': '1.93',
  '2019/08': '1.97',
  '2019/09': '1.98',
  '2019/10': '2.05',
  '2019/11': '2.15'},
 'NMHC': {'2019/01': '0.27',
  '2019/02': '0.17',
  '2019/03': '0.18',
  '2019/04': '0.14',
  '2019/05': '0.16',
  '2019/06': '0.13',
  '2019/07': '0.14',
  '2019/08': '0.15',
  '2019/09': '0.13',
  '2019/10': '0.13',
  '2019/11': '0.21'},
 'CH4': {'2019/01': '2',
  '2019/02': '1.94',
  '2019/03': '1.94',
  '2019/04': '1.88',
  '2019/05': '1.86',
  '2019/06': '1.79',
  '2019/07': '1.80',
  '2019/08': '1.82',
  '2019/09': '1.86',
  '2019/10': '1.92',
  '2019/11': '1.94'}}

In [5]:
import pandas as pd
pd.DataFrame(d)

          SO2    CO     O3 PM10    NOx    NO    NO2   THC  NMHC   CH4
2019/01  4.10  0.67  24.70   78  38.01  7.95  30.06  2.27  0.27     2
2019/02  3.30  0.48  29.40   57  25.62  4.76  20.86  2.11  0.17  1.94
2019/03  3.90  0.50  29.20   52  27.84  5.41  22.43  2.12  0.18  1.94
2019/04  3.40  0.39  30.40   42  21.83  4.16  17.68  2.02  0.14  1.88
2019/05  3.30  0.38  28.60   35  22.55  4.58  17.98  2.02  0.16  1.86
2019/06  4.10  0.24  16.30   20  17.15  5.08  12.08  1.92  0.13  1.79
2019/07     4  0.28  15.50   24  17.71  5.16  12.54  1.93  0.14  1.80
2019/08  4.60  0.33  19.70   27  19.66  5.17  14.49  1.97  0.15  1.82
2019/09  3.50  0.32  35.70   35  18.66  3.63  15.03  1.98  0.13  1.86
2019/10  3.20  0.36     44   50  19.50  3.50  15.99  2.05  0.13  1.92
2019/11  3.60  0.46  34.80   63  28.99  5.21  23.78  2.15  0.21  1.94